from pathlib import Path
import re
p = Path("DeltaCustomizationModule.luau")
s = p.read_text()
marker = '\tlocal normalizingTabs = false\n\tlocal function normalizeSavedTabFiles()\n'
insert = '\tlocal normalizingTabs = false\n\tlocal managedCloseBound = setmetatable({}, { __mode = "k" })\n\tlocal managedCloseBusy = setmetatable({}, { __mode = "k" })\n\tlocal normalizeTabSequence\n\n\tlocal function getOrderedTabButtons()\n\t\tlocal entries = {}\n\t\tfor ordinal, tab in tabsFrame:GetChildren() do\n\t\t\tif tab:IsA("GuiButton") and tab.Name:match("^script%d+%.lua$") then\n\t\t\t\ttable.insert(entries, { tab = tab, ordinal = ordinal })\n\t\t\tend\n\t\tend\n\t\ttable.sort(entries, function(a, b)\n\t\t\tlocal ao = a.tab.LayoutOrder\n\t\t\tlocal bo = b.tab.LayoutOrder\n\t\t\tif ao ~= bo then\n\t\t\t\treturn ao < bo\n\t\t\tend\n\t\t\tlocal ai = tonumber(a.tab.Name:match("%d+")) or math.huge\n\t\t\tlocal bi = tonumber(b.tab.Name:match("%d+")) or math.huge\n\t\t\tif ai ~= bi then\n\t\t\t\treturn ai < bi\n\t\t\tend\n\t\t\treturn a.ordinal < b.ordinal\n\t\tend)\n\t\tlocal result = {}\n\t\tfor _, entry in entries do\n\t\t\ttable.insert(result, entry.tab)\n\t\tend\n\t\treturn result\n\tend\n\n\tlocal function closeManagedTab(tab)\n\t\tif not (runtime.alive and tab and tab.Parent) then\n\t\t\treturn\n\t\tend\n\t\tlocal tabs = getOrderedTabButtons()\n\t\tif #tabs <= 1 then\n\t\t\treturn\n\t\tend\n\t\tlocal index = table.find(tabs, tab)\n\t\tif not index then\n\t\t\treturn\n\t\tend\n\t\tlocal boxes = getCodeBoxes()\n\t\tlocal box = boxes[index]\n\t\tlocal wasVisible = box and box.Visible or false\n\t\tif tab.Parent then\n\t\t\ttab:Destroy()\n\t\tend\n\t\tif box and box.Parent then\n\t\t\tbox:Destroy()\n\t\tend\n\t\ttask.defer(function()\n\t\t\tif not runtime.alive then\n\t\t\t\treturn\n\t\t\tend\n\t\t\tnormalizeTabSequence()\n\t\t\tif wasVisible then\n\t\t\t\tlocal remaining = getCodeBoxes()\n\t\t\t\tlocal nextBox = remaining[math.min(index, #remaining)] or remaining[#remaining]\n\t\t\t\tif nextBox then\n\t\t\t\t\tfor _, current in remaining do\n\t\t\t\t\t\tcurrent.Visible = current == nextBox\n\t\t\t\t\tend\n\t\t\t\t\tfor _, currentTab in getOrderedTabButtons() do\n\t\t\t\t\t\tcurrentTab.BackgroundTransparency = currentTab.Name == nextBox.Name and 0 or 1\n\t\t\t\t\tend\n\t\t\t\tend\n\t\t\tend\n\t\t\tqueueStatusUpdate()\n\t\tend)\n\tend\n\n\tlocal function bindManagedClose(tab)\n\t\tif not (tab and tab:IsA("GuiButton")) or managedCloseBound[tab] then\n\t\t\treturn\n\t\tend\n\t\tlocal closeButton = tab:FindFirstChild("ImageButton")\n\t\tif not (closeButton and closeButton:IsA("GuiButton")) then\n\t\t\treturn\n\t\tend\n\t\tmanagedCloseBound[tab] = true\n\t\tlocal function activateClose()\n\t\t\tif managedCloseBusy[tab] then\n\t\t\t\treturn\n\t\t\tend\n\t\t\tmanagedCloseBusy[tab] = true\n\t\t\tcloseManagedTab(tab)\n\t\t\ttask.delay(0.1, function()\n\t\t\t\tmanagedCloseBusy[tab] = nil\n\t\t\tend)\n\t\tend\n\t\tconnect(closeButton.MouseButton1Click, activateClose)\n\t\tconnect(closeButton.Activated, activateClose)\n\tend\n\n\tlocal function normalizeSavedTabFiles()\n'
if marker not in s:
    raise SystemExit("normalizer marker not found")
s = s.replace(marker, insert, 1)
pattern = re.compile(r'\tlocal function normalizeTabSequence\(\)\n.*?\n\tend\n\n\tlocal function savedTabNames\(\)', re.S)
replacement = '\tnormalizeTabSequence = function()\n\t\tif normalizingTabs or not runtime.alive then\n\t\t\treturn\n\t\tend\n\t\tnormalizingTabs = true\n\t\tlocal boxes = getCodeBoxes()\n\t\tlocal tabs = getOrderedTabButtons()\n\t\tlocal usedTabs = setmetatable({}, { __mode = "k" })\n\t\tlocal entries = {}\n\t\tlocal keep = {}\n\t\tfor index, box in boxes do\n\t\t\tlocal oldName = box.Name\n\t\t\tlocal newName = "script" .. tostring(index) .. ".lua"\n\t\t\tkeep[newName] = true\n\t\t\tlocal tab\n\t\t\tfor _, candidate in tabs do\n\t\t\t\tif not usedTabs[candidate] and candidate.Name == oldName then\n\t\t\t\t\ttab = candidate\n\t\t\t\t\tbreak\n\t\t\t\tend\n\t\t\tend\n\t\t\tif not tab then\n\t\t\t\tfor _, candidate in tabs do\n\t\t\t\t\tif not usedTabs[candidate] then\n\t\t\t\t\t\ttab = candidate\n\t\t\t\t\t\tbreak\n\t\t\t\t\tend\n\t\t\t\tend\n\t\t\tend\n\t\t\tif tab then\n\t\t\t\tusedTabs[tab] = true\n\t\t\tend\n\t\t\ttable.insert(entries, {\n\t\t\t\tbox = box,\n\t\t\t\ttab = tab,\n\t\t\t\toldName = oldName,\n\t\t\t\tnewName = newName,\n\t\t\t\ttext = box.Text or "",\n\t\t\t})\n\t\tend\n\t\tfor _, tab in tabs do\n\t\t\tif not usedTabs[tab] and tab.Parent then\n\t\t\t\ttab:Destroy()\n\t\t\tend\n\t\tend\n\t\tfor index, entry in entries do\n\t\t\tif entry.box.Parent then\n\t\t\t\tentry.box.Name = entry.newName\n\t\t\tend\n\t\t\tlocal tab = entry.tab\n\t\t\tif tab and tab.Parent then\n\t\t\t\ttab.Name = entry.newName\n\t\t\t\ttab.LayoutOrder = index\n\t\t\t\tlocal title = tab:FindFirstChild("Title", true)\n\t\t\t\tif title and title:IsA("TextLabel") then\n\t\t\t\t\ttitle.Text = entry.newName\n\t\t\t\tend\n\t\t\t\tbindManagedClose(tab)\n\t\t\tend\n\t\tend\n\t\tif type(writefile) == "function" then\n\t\t\tfor _, entry in entries do\n\t\t\t\tpcall(writefile, tabDirectory .. "/" .. entry.newName, entry.text)\n\t\t\tend\n\t\tend\n\t\tif type(delfile) == "function" and type(isfile) == "function" then\n\t\t\tfor _, entry in entries do\n\t\t\t\tif entry.oldName ~= entry.newName and not keep[entry.oldName] then\n\t\t\t\t\tlocal path = tabDirectory .. "/" .. entry.oldName\n\t\t\t\t\tif isfile(path) then\n\t\t\t\t\t\tpcall(delfile, path)\n\t\t\t\t\tend\n\t\t\t\tend\n\t\t\tend\n\t\tend\n\t\tqueueStatusUpdate()\n\t\tnormalizingTabs = false\n\tend\n\n\tlocal function savedTabNames()'
s, count = pattern.subn(replacement, s, count=1)
if count != 1:
    raise SystemExit(f"normalize block replacements: {count}")
p.write_text(s)
